### ISSUE TITLE
USBSerial.print('A'); causes compile error

### ISSUE THREAD

**Issue by teastainGit** [m5stack/M5AtomS3#14]
### Describe the bug
(Similar to Sarah-C three weeks ago but I uninstalled ver 2.0.5 and re-installed.)
Library >Arduino15 › packages > m5stack > hardware > esp32 >2.0.6
No other old M5Stack versions left over.
Deleted the AtomS3 Library and re-installed fresh from your repository.)

PROBLEM:
In the example from your GitHub repository  "Button.ino"  (and all the examples) produces a compile error:

                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/terrystainton/Documents/Arduino/libraries/M5AtomS3-main/examples/Basics/Button/Button.ino: In function 'void loop()':
/Users/terrystainton/Documents/Arduino/libraries/M5AtomS3-main/examples/Basics/Button/Button.ino:32:9: error: 'USBSerial' was not declared in this scope
         USBSerial.print('A');
         ^~~~~~~~~
/Users/terrystainton/Documents/Arduino/libraries/M5AtomS3-main/examples/Basics/Button/Button.ino:32:9: note: suggested alternative: 'Serial'
         USBSerial.print('A');
         ^~~~~~~~~
         Serial

exit status 1

Compilation error: 'USBSerial' was not declared in this scope

### To reproduce

iMac 24-inch, M1, 2021
Chip Apple M1
Memory 16 GB
Startup disk Macintosh HD
 macOS Ventura 13.1

### Expected behavior

upload and run 

### Environment

- OS:iMac 24-inch, M1, 2021 Chip Apple M1 Memory 16 GB macOS Ventura 13.1

- IDE &IDE Version: Arduino V2.0.3
- Repository Version: M5Stack ver 2.0.6
M5AtomS3 Version 0.0.2

### Additional context

10 years Arduino, 3 years M5Stack experience

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Perhaps there is a local cache package that is not downloading the latest M5Stack version definition
Please delete the following path, uninstall the M5Stack 2.0.6 definition and try again
/Users/<Username>/Library/Arduino15/staging/packages

**Comment by teastainGit** [comment]
Tinyu: Thank you very much, problem, solved!
-Terry
