### ISSUE TITLE
In the AtomS3 examples what does the LED.ino sketch do?

### ISSUE THREAD

**Issue by teastainGit** [m5stack/M5AtomS3#15]
### Describe the bug

I run the LED.ino sketch and it does nothing.
I think maybe sketch from old Aton Matrix?
If so, please remove as it confuses new users.

### To reproduce

upload sketch

### Expected behaviour

Should display something?

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by teastainGit** [comment]
No response so please close.

**Comment by Tinyu-Zhao** [comment]
Sorry, my negligence is not clearly marked, only AtomS3Lite has RGB lights.
