### ISSUE TITLE
Sprite missing

### ISSUE THREAD

**Issue by sonic74** [m5stack/M5AtomS3#18]
Would be really nice to have
https://github.com/m5stack/M5AtomS3/blob/50291dcb9dd7f618d9576780f277708df4aeac84/src/M5Display.h#L8
like on M5StickC Plus & Core2

**Comment by sonic74** [comment]
I just discovered point 6 of
https://github.com/Bodmer/TFT_eSPI/blob/f35f57ade199c3a5774f36b0d5b6b9175392994e/README.md
which is an alternative at least for text.

**Comment by Tinyu-Zhao** [comment]
Now with M5GFX as an alternative, it will be better.
