### ISSUE TITLE
Cannot compile the FactoryTest Example

### ISSUE THREAD

**Issue by NAVspecialist** [m5stack/M5AtomS3#21]
### Describe the bug

Hello

Some input would be much appreciated.

I am getting an error saying :

Resolving ATOMS3 dependencies...
Tool Manager: Installing espressif/toolchain-riscv32-esp @ 8.4.0+2021r2-patch3
Error: Could not find the package with 'espressif/toolchain-riscv32-esp @ 8.4.0+2021r2-patch3' requirements for your system 'windows_amd64'

### To reproduce

I am running Windows 11 with Visual Studio Code version 1.78.2 Installed and then I Installed the latest plugin Platform Io.

1) Downloaded the Zip file here:
https://github.com/m5stack/M5AtomS3/releases/tag/0.0.3

2) Then I unpacked it to the project folder.

3) Opened VSC, and then I started the Platform.IO
4) In Home I opended the Factory Test Folder.

5) Selected Dependencies (a: list, b: Outdated and then c: update)

Resolving ATOMS3 dependencies...
Platform espressif32 @ 5.2.0 (required: espressif32 @ 5.2.0)
└── toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch3 (required: espressif/toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch3)

6) Tried to click on Build but got the message:

rocessing ATOMS3 (platform: espressif32@5.2.0; framework: arduino; board: esp32-s3-devkitc-1)
----------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing espressif/toolchain-riscv32-esp @ 8.4.0+2021r2-patch3
Error: Could not find the package with 'espressif/toolchain-riscv32-esp @ 8.4.0+2021r2-patch3' requirements for your system 'windows_amd64'

So the question is does it work if I switch to Ubunto so the problem is windows-only-related (due to the Windows_amd64 message) ? 

Thanks.

### Expected behavior

That I could compile the FactoryTest app.

### Environment

- OS: WIndows 
- IDE &IDE Version: Visual Studio Code 1.78.2
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Received, I will test it.

**Comment by Tinyu-Zhao** [comment]
[FactoryTest](https://github.com/m5stack/M5AtomS3/tree/main/examples/Basics/FactoryTest) is a standalone Platfrom IO project, please open it in a clean vscode workspace and compile it.

<img width="1461" alt="image" src="https://github.com/m5stack/M5AtomS3/assets/44396641/28924505-d14c-4be0-a184-a0fe45203e98">

**Comment by NAVspecialist** [comment]
Not sure I understand because I still get the same error. Here is what I did

1) In the project folder copied the FactoryTest folder
 (C:\Users\Palle\OneDrive-OLD\Dokumenter\PlatformIO\Projects\FactoryTest)
 
2) In VSC, File, Open Folder 
 C:\Users\Palle\OneDrive-OLD\Dokumenter\PlatformIO\Projects\ and seleted FactoryTest

3) I opened the Main.cpp file
4) Pressed Control+Shift+P - PlatformIO: Clean
5) Pressed Control+Shift+P - PlatformIO: Build

And then I still get the same error

**Comment by Tinyu-Zhao** [comment]
<img width="767" alt="image" src="https://github.com/m5stack/M5AtomS3/assets/44396641/736b05d9-a34d-4f26-9bd9-fd252f6a9297">

Maybe your problem is related to the esp32 toolchain, you can try uninstalling these and try installing them again.
In addition, if you still can't compile successfully, you can ask the [esp32 official](https://github.com/espressif/arduino-esp32) for more professional advice on configuring the compilation environment

<img width="1461" alt="image" src="https://github.com/m5stack/M5AtomS3/assets/44396641/02715867-3621-4420-b549-630d5a750d1a">
