### ISSUE TITLE
Out of Date doesn't work with Arudino Current Version

### ISSUE THREAD

**Issue by RamboRogers** [m5stack/M5AtomS3#28]
### Describe the bug

Codes compiles but ESP32 throws this error when using demo code.

E (162) rmt(legacy): CONFLICT! driver_ng is not allowed to be usE (162) rmt(legacy): CONFLICT! driver_ng is not allowed to be used with the 

### To reproduce

Try to compile demo code on Arduino using current libraries.

### Expected behavior

Code works.

### Screenshots

![image](https://github.com/user-attachments/assets/65de0c18-c315-4ffe-92b7-fd4f399ff3db)
![image](https://github.com/user-attachments/assets/e4560127-ca2d-4912-80f1-bc471e1abab4)
![image](https://github.com/user-attachments/assets/a7425b62-d0eb-4a63-a56a-3a9d99b78105)

### Environment

- OS: MacOS 
- IDE &IDE Version: Arduino 2.3.2
- Repository Version: M5AtomS3 0.1.2

### Additional context

It looks like M5 Unified compiles. Maybe it was fixed and this wasn't?

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Are you using AtomS3 in the esp32 board or AtomS3 in the m5stack board?

**Comment by RamboRogers** [comment]
You are right, I'm using the ESP32 board.  Thank you!
